(cl:in-package vrm3dvision-msg)
(cl:export '(LEAF_SIZE-VAL
          LEAF_SIZE
          NORMAL_RADIUS_RATIO_LEAF-VAL
          NORMAL_RADIUS_RATIO_LEAF
          FEATURE_RADIUS_RATIO_LEAF-VAL
          FEATURE_RADIUS_RATIO_LEAF
          CORRESPONDENCE_RANDOMNESS-VAL
          CORRESPONDENCE_RANDOMNESS
          SIMILARITY_THRESHOLD-VAL
          SIMILARITY_THRESHOLD
          MAX_ITERATIONS-VAL
          MAX_ITERATIONS
          MAX_CORRESPONDENCE_DISTANCE_RATIO_LEAF-VAL
          MAX_CORRESPONDENCE_DISTANCE_RATIO_LEAF
          INLIER_FRACTION-VAL
          INLIER_FRACTION
          ICP_MAX_ITERATIONS-VAL
          ICP_MAX_ITERATIONS
          ICP_MAX_CORRESPONDENCE_DISTANCE_RATIO_LEAF-VAL
          ICP_MAX_CORRESPONDENCE_DISTANCE_RATIO_LEAF
          MIN_SCORE-VAL
          MIN_SCORE
          MIN_SCORE_THRESHOLD-VAL
          MIN_SCORE_THRESHOLD
))