/* Auto-generated by genmsg_cpp for file /home/jeppe/workspace-d3/robovision3d/host/vrm3dvision/srv/startCamera.srv */
#ifndef VRM3DVISION_SERVICE_STARTCAMERA_H
#define VRM3DVISION_SERVICE_STARTCAMERA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrm3dvision
{
template <class ContainerAllocator>
struct startCameraRequest_ {
  typedef startCameraRequest_<ContainerAllocator> Type;

  startCameraRequest_()
  : camera(0)
  {
  }

  startCameraRequest_(const ContainerAllocator& _alloc)
  : camera(0)
  {
  }

  typedef int8_t _camera_type;
  int8_t camera;

  enum { LEFT_CAMERA = 1 };
  enum { RIGHT_CAMERA = 2 };
  enum { COLOR_CAMERA = 4 };
  enum { ALL_CAMERAS = 8 };

  typedef boost::shared_ptr< ::vrm3dvision::startCameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrm3dvision::startCameraRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct startCameraRequest
typedef  ::vrm3dvision::startCameraRequest_<std::allocator<void> > startCameraRequest;

typedef boost::shared_ptr< ::vrm3dvision::startCameraRequest> startCameraRequestPtr;
typedef boost::shared_ptr< ::vrm3dvision::startCameraRequest const> startCameraRequestConstPtr;



template <class ContainerAllocator>
struct startCameraResponse_ {
  typedef startCameraResponse_<ContainerAllocator> Type;

  startCameraResponse_()
  : success(false)
  {
  }

  startCameraResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::vrm3dvision::startCameraResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrm3dvision::startCameraResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct startCameraResponse
typedef  ::vrm3dvision::startCameraResponse_<std::allocator<void> > startCameraResponse;

typedef boost::shared_ptr< ::vrm3dvision::startCameraResponse> startCameraResponsePtr;
typedef boost::shared_ptr< ::vrm3dvision::startCameraResponse const> startCameraResponseConstPtr;


struct startCamera
{

typedef startCameraRequest Request;
typedef startCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct startCamera
} // namespace vrm3dvision

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrm3dvision::startCameraRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrm3dvision::startCameraRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrm3dvision::startCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9555ddfe79f9f785c9380537f71d585a";
  }

  static const char* value(const  ::vrm3dvision::startCameraRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9555ddfe79f9f785ULL;
  static const uint64_t static_value2 = 0xc9380537f71d585aULL;
};

template<class ContainerAllocator>
struct DataType< ::vrm3dvision::startCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrm3dvision/startCameraRequest";
  }

  static const char* value(const  ::vrm3dvision::startCameraRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrm3dvision::startCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 LEFT_CAMERA = 1\n\
int8 RIGHT_CAMERA = 2\n\
int8 COLOR_CAMERA = 4\n\
int8 ALL_CAMERAS = 8\n\
\n\
int8 camera\n\
\n\
";
  }

  static const char* value(const  ::vrm3dvision::startCameraRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrm3dvision::startCameraRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrm3dvision::startCameraResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrm3dvision::startCameraResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrm3dvision::startCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::vrm3dvision::startCameraResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrm3dvision::startCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrm3dvision/startCameraResponse";
  }

  static const char* value(const  ::vrm3dvision::startCameraResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrm3dvision::startCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrm3dvision::startCameraResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrm3dvision::startCameraResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrm3dvision::startCameraRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.camera);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct startCameraRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrm3dvision::startCameraResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct startCameraResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrm3dvision::startCamera> {
  static const char* value() 
  {
    return "7ab4d71c90564909e360a8b8d9fc499c";
  }

  static const char* value(const vrm3dvision::startCamera&) { return value(); } 
};

template<>
struct DataType<vrm3dvision::startCamera> {
  static const char* value() 
  {
    return "vrm3dvision/startCamera";
  }

  static const char* value(const vrm3dvision::startCamera&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrm3dvision::startCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ab4d71c90564909e360a8b8d9fc499c";
  }

  static const char* value(const vrm3dvision::startCameraRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrm3dvision::startCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrm3dvision/startCamera";
  }

  static const char* value(const vrm3dvision::startCameraRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrm3dvision::startCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ab4d71c90564909e360a8b8d9fc499c";
  }

  static const char* value(const vrm3dvision::startCameraResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrm3dvision::startCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrm3dvision/startCamera";
  }

  static const char* value(const vrm3dvision::startCameraResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VRM3DVISION_SERVICE_STARTCAMERA_H

