/* Auto-generated by genmsg_cpp for file /home/jeppe/workspace-d3/robovision3d/host/vrm3dvision/srv/stopCamera.srv */
#ifndef VRM3DVISION_SERVICE_STOPCAMERA_H
#define VRM3DVISION_SERVICE_STOPCAMERA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrm3dvision
{
template <class ContainerAllocator>
struct stopCameraRequest_ {
  typedef stopCameraRequest_<ContainerAllocator> Type;

  stopCameraRequest_()
  : camera(0)
  {
  }

  stopCameraRequest_(const ContainerAllocator& _alloc)
  : camera(0)
  {
  }

  typedef int8_t _camera_type;
  int8_t camera;

  enum { LEFT_CAMERA = 1 };
  enum { RIGHT_CAMERA = 2 };
  enum { COLOR_CAMERA = 4 };
  enum { ALL_CAMERAS = 8 };

  typedef boost::shared_ptr< ::vrm3dvision::stopCameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrm3dvision::stopCameraRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct stopCameraRequest
typedef  ::vrm3dvision::stopCameraRequest_<std::allocator<void> > stopCameraRequest;

typedef boost::shared_ptr< ::vrm3dvision::stopCameraRequest> stopCameraRequestPtr;
typedef boost::shared_ptr< ::vrm3dvision::stopCameraRequest const> stopCameraRequestConstPtr;



template <class ContainerAllocator>
struct stopCameraResponse_ {
  typedef stopCameraResponse_<ContainerAllocator> Type;

  stopCameraResponse_()
  : success(false)
  {
  }

  stopCameraResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::vrm3dvision::stopCameraResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrm3dvision::stopCameraResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct stopCameraResponse
typedef  ::vrm3dvision::stopCameraResponse_<std::allocator<void> > stopCameraResponse;

typedef boost::shared_ptr< ::vrm3dvision::stopCameraResponse> stopCameraResponsePtr;
typedef boost::shared_ptr< ::vrm3dvision::stopCameraResponse const> stopCameraResponseConstPtr;


struct stopCamera
{

typedef stopCameraRequest Request;
typedef stopCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct stopCamera
} // namespace vrm3dvision

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrm3dvision::stopCameraRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrm3dvision::stopCameraRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrm3dvision::stopCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9555ddfe79f9f785c9380537f71d585a";
  }

  static const char* value(const  ::vrm3dvision::stopCameraRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9555ddfe79f9f785ULL;
  static const uint64_t static_value2 = 0xc9380537f71d585aULL;
};

template<class ContainerAllocator>
struct DataType< ::vrm3dvision::stopCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrm3dvision/stopCameraRequest";
  }

  static const char* value(const  ::vrm3dvision::stopCameraRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrm3dvision::stopCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 LEFT_CAMERA = 1\n\
int8 RIGHT_CAMERA = 2\n\
int8 COLOR_CAMERA = 4\n\
int8 ALL_CAMERAS = 8\n\
\n\
int8 camera\n\
\n\
";
  }

  static const char* value(const  ::vrm3dvision::stopCameraRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrm3dvision::stopCameraRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrm3dvision::stopCameraResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrm3dvision::stopCameraResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrm3dvision::stopCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::vrm3dvision::stopCameraResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrm3dvision::stopCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrm3dvision/stopCameraResponse";
  }

  static const char* value(const  ::vrm3dvision::stopCameraResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrm3dvision::stopCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrm3dvision::stopCameraResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrm3dvision::stopCameraResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrm3dvision::stopCameraRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.camera);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct stopCameraRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrm3dvision::stopCameraResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct stopCameraResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrm3dvision::stopCamera> {
  static const char* value() 
  {
    return "7ab4d71c90564909e360a8b8d9fc499c";
  }

  static const char* value(const vrm3dvision::stopCamera&) { return value(); } 
};

template<>
struct DataType<vrm3dvision::stopCamera> {
  static const char* value() 
  {
    return "vrm3dvision/stopCamera";
  }

  static const char* value(const vrm3dvision::stopCamera&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrm3dvision::stopCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ab4d71c90564909e360a8b8d9fc499c";
  }

  static const char* value(const vrm3dvision::stopCameraRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrm3dvision::stopCameraRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrm3dvision/stopCamera";
  }

  static const char* value(const vrm3dvision::stopCameraRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrm3dvision::stopCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ab4d71c90564909e360a8b8d9fc499c";
  }

  static const char* value(const vrm3dvision::stopCameraResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrm3dvision::stopCameraResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrm3dvision/stopCamera";
  }

  static const char* value(const vrm3dvision::stopCameraResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VRM3DVISION_SERVICE_STOPCAMERA_H

